# Generated by Django 3.1.2 on 2021-08-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfilo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='img3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
