# Generated by Django 3.1.2 on 2021-08-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfilo', '0002_projectdetail_img3'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='des',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='heading',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='project_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='project_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
