# Generated by Django 3.1.2 on 2021-08-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfilo', '0004_auto_20210820_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.CharField(blank=True, max_length=100, null=True)),
                ('img1', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
